task default: [:install]

BASE_PATH = '/usr/share/X11/xkb/'
SYMB_PATH = File.join(BASE_PATH, 'symbols')
RULE_PATH = File.join(BASE_PATH, 'rules')
lst_files = xml_files = ['base', 'evdev', 'xfree86', 'xorg']

LST_FILES = lst_files.map {|f| File.join(RULE_PATH, f)+'.lst'}
XML_FILES = xml_files.map {|f| File.join(RULE_PATH, f)+'.xml'}
SYMB_FILE = File.join(SYMB_PATH, 'de')
$modified = 0

task :install => [:lst_files, :xml_files, :symb_file] do
  if $modified >= 5
    puts "Changed #{$modified} files in total. Looks good!"
  elsif Process.uid != 0 
    puts "Error: this task must be run as root. Try again prepending \"sudo\"!"
  elsif `grep -r 'dmg' #{SYMB_PATH} #{RULE_PATH} | wc -l`.to_i < 5
    puts "Something went wrong. Please contact us by creating an Issue on the GitHub project."
    puts "providing information on your distribution (including the version) and, if possible,"
    puts "a screenshot of your terminal window at this point."
  else
    puts "Seems de_dmg is already installed..."
  end
  puts
end

task :lst_files do
  LST_FILES.each do |fn|
    next unless File.exist?(fn)
    unless File.read(fn) =~ /dmg/
      apline =  `grep -n 'de: ' #{fn} | tail -1 | cut -d ':' -f 1`.strip.to_i
      string = `cat rules/insert.lst | tail -1`.strip
      print "Inserting into #{fn}... "
      if system("sed -i '#{apline}i  #{string}' #{fn}")
        print "done\n"
        $modified += 1
      end
    end
  end
end

task :xml_files do
  XML_FILES.each do |fn|
    next unless File.exist?(fn)
    unless File.read(fn) =~ /dmg/
      tmpfn = File.join('/tmp', File.basename(fn))
      print "Inserting into #{fn}... "
      if system("xsltproc rules/insert.xslt #{fn} > #{tmpfn}")
        if system("cp #{tmpfn} #{fn}")
          print "done\n"
          $modified += 1
        end
      end
    end
  end
end

task :symb_file do
  fn = SYMB_FILE
  unless File.read(fn) =~ /dmg/
    print "Inserting into #{fn}... "
    if system("echo >> #{fn}")
      if system("cat symbols/de >> #{fn}")
        print "done\n"
        $modified += 1
      end
    end
  end
end
